# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9edd71ca8b501edffcbb3b47bbcb6da4614553d47df65229f4402fcb496e57dc5469768a3cec8cc9816d6e05fa3cdb5ba65ca19940ddd0d38f79938c3d5985fc

test:
  secret_key_base: 939477cad4bab852a25fb932a541dd6c6d2727ff65fb1f8257c95c18d77a2d5e3495a271479d50640eaf79a3d4c47b00842f1faa2542480d6b86ee04e6070dba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
